name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cfg:
        - { ruby: 3.0.7, postgres: 14, gemfile: rails_6.0 }
        - { ruby: 3.0.7, postgres: 15, gemfile: rails_6.0 }
        - { ruby: 3.0.7, postgres: 16, gemfile: rails_6.0 }

        - { ruby: 3.0.7, postgres: 14, gemfile: rails_6.1 }
        - { ruby: 3.0.7, postgres: 15, gemfile: rails_6.1 }
        - { ruby: 3.0.7, postgres: 16, gemfile: rails_6.1 }

        - { ruby: 3.0.7, postgres: 14, gemfile: rails_7.0 }
        - { ruby: 3.0.7, postgres: 15, gemfile: rails_7.0 }
        - { ruby: 3.0.7, postgres: 16, gemfile: rails_7.0 }

        - { ruby: 3.1.6, postgres: 14, gemfile: rails_7.0 }
        - { ruby: 3.1.6, postgres: 15, gemfile: rails_7.0 }
        - { ruby: 3.1.6, postgres: 16, gemfile: rails_7.0 }

        - { ruby: 3.0.7, postgres: 14, gemfile: rails_7.1 }
        - { ruby: 3.0.7, postgres: 15, gemfile: rails_7.1 }
        - { ruby: 3.1.6, postgres: 14, gemfile: rails_7.1 }
        - { ruby: 3.1.6, postgres: 15, gemfile: rails_7.1 }
        - { ruby: 3.1.6, postgres: 16, gemfile: rails_7.1 }

        - { ruby: 3.1.6, postgres: 14, gemfile: rails_7.2 }
        - { ruby: 3.1.6, postgres: 15, gemfile: rails_7.2 }
        - { ruby: 3.2.6, postgres: 14, gemfile: rails_7.2 }
        - { ruby: 3.2.6, postgres: 15, gemfile: rails_7.2 }
        - { ruby: 3.2.6, postgres: 16, gemfile: rails_7.2 }

    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.cfg.gemfile }}.gemfile
    services:
      postgres:
        image: postgres:${{ matrix.cfg.postgres }}
        ports:
        - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: conflict_free_schema
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ${{ matrix.cfg.ruby }}
    - name: Install dependencies
      run: bundle install
    - name: Update postgres
      run: |
        sudo sh -c 'echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
        sudo apt-get update && sudo apt-get install postgresql-client-16
    - name: Run tests
      run: bundle exec rspec
      env:
        POSTGRES_HOST: localhost
        RAILS_ENV: test
